import{a as b,i as l,S as M}from"./assets/vendor-DjDxajEQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=a(e);fetch(e.href,r)}})();function u(s,o){const a=s.map(({webformatURL:i,largeImageURL:e,tags:r,likes:n,views:m,comments:g,downloads:L})=>`
              <li class="gallery-item">
                  <a href="${e}" class="gallery-link">
                      <img src="${i}" alt="${r}" class="gallery-image" />
                  </a>
                  <div class="info">
                      <p class="info-item"><span>Likes</span> ${n}</p>
                      <p class="info-item"><span>Views</span> ${m}</p>
                      <p class="info-item"><span>Comments</span> ${g}</p>
                      <p class="info-item"><span>Downloads</span> ${L}</p>
                  </div>
              </li>`).join("");o.insertAdjacentHTML("beforeend",a)}const E="https://pixabay.com/api/",S="46090964-55e0ede1337bbc868df4332a0",h=15;async function y(s,o=1){const a=new URLSearchParams({q:s,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:h,page:o}),i=`${E}?key=${S}&${a}`;try{const{data:{hits:e,totalHits:r},request:{status:n}}=await b.get(i);return(n!==200||e.length===0)&&(refs.loadMoreBtn.classList.add("is-hidden"),refs.loader.style.display="none",l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})),{hits:e,totalHits:r}}catch{refs.loadMoreBtn.classList.add("is-hidden"),refs.loader.style.display="none",l.error({title:"Error",message:"Something went wrong",position:"topRight"})}}const f=new M(".js-gallery a",{captionsData:"alt",captionDelay:250});let c=1,d=null,p=0;const t={form:document.querySelector(".js-form"),container:document.querySelector(".js-container"),searchBtn:document.querySelector(".js-search-btn"),loadMoreBtn:document.querySelector(".js-load-more-btn"),gallery:document.querySelector(".js-gallery"),loader:document.getElementById("loader")};t.form.addEventListener("submit",B);t.loadMoreBtn.addEventListener("click",w);async function B(s){s.preventDefault();const o=s.currentTarget;if(d=o.elements.query.value.trim(),t.gallery.innerHTML="",c=1,t.loader.style.display="block",t.loadMoreBtn.classList.add("is-hidden"),!d){l.error({title:"Error",message:"Please enter a search query.",position:"topRight"}),t.loader.style.display="none";return}try{const{hits:a,totalHits:i}=await y(d,c);p=Math.ceil(i/h),u(a,t.gallery),i>h&&t.loadMoreBtn.classList.remove("is-hidden"),c>=Math.min(p,34)&&(t.loadMoreBtn.classList.add("is-hidden"),l.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"})),o.reset(),f.refresh()}catch{l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"})}finally{t.loader.style.display="none"}}async function w(){c+=1,t.loader.style.display="block";try{t.loadMoreBtn.classList.remove("is-hidden");const{hits:s}=await y(d,c);u(s,t.gallery),q(),f.refresh(),c>=Math.min(p,34)&&(t.loadMoreBtn.classList.add("is-hidden"),l.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"}))}catch(s){console.error(s)}finally{t.loader.style.display="none"}}function q(){const a=t.gallery.lastElementChild.getBoundingClientRect().height*2;window.scrollBy({top:a,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
