import{a as L,i as c,S as b}from"./assets/vendor-DjDxajEQ.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();function p(r,o){const s=r.map(({webformatURL:n,largeImageURL:e,tags:t,likes:a,views:m,comments:g,downloads:y})=>`
              <li class="gallery-item">
                  <a href="${e}" class="gallery-link">
                      <img src="${n}" alt="${t}" class="gallery-image" />
                  </a>
                  <div class="info">
                      <p class="info-item"><span>Likes</span> ${a}</p>
                      <p class="info-item"><span>Views</span> ${m}</p>
                      <p class="info-item"><span>Comments</span> ${g}</p>
                      <p class="info-item"><span>Downloads</span> ${y}</p>
                  </div>
              </li>`).join("");o.insertAdjacentHTML("beforeend",s)}const w="https://pixabay.com/api/",S="46090964-55e0ede1337bbc868df4332a0",d=15;async function f(r,o=1){const s=new URLSearchParams({q:r,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:d,page:o}),n=`${w}?key=${S}&${s}`,{data:{hits:e,totalHits:t},request:{status:a}}=await L.get(n);return a!==200&&c.error({title:"Error",message:"Something went wrong...",position:"topRight"}),e.length===0&&c.error({title:"Error",message:"Something went wrong...",position:"topRight"}),{hits:e,totalHits:t}}let l=1,u=null,h=0;const i={form:document.querySelector(".js-form"),container:document.querySelector(".js-container"),searchBtn:document.querySelector(".js-search-btn"),loadMoreBtn:document.querySelector(".js-load-more-btn"),gallery:document.querySelector(".js-gallery")};i.form.addEventListener("submit",M);i.loadMoreBtn.addEventListener("click",v);async function M(r){r.preventDefault();const o=r.currentTarget;u=o.elements.query.value,i.gallery.innerHTML="",l=1;try{const{hits:s,totalHits:n}=await f(u,l);h=Math.ceil(n/d),p(s,i.gallery),n>d&&i.loadMoreBtn.classList.remove("is-hidden");const e=new b(".js-gallery a",{captionsData:"alt",captionDelay:250})}catch{}finally{o.reset()}}async function v(){l+=1;try{i.loadMoreBtn.classList.remove("is-hidden");const{hits:r}=await f(u,l);p(r,i.gallery),E(),lightbox.refresh(),l>=Math.min(h,34)&&(i.loadMoreBtn.classList.add("is-hidden"),c.error({title:"Error",message:"We are sorry, but you have reached the end of search results.",position:"topRight"}))}catch(r){console.error(r)}finally{}}function E(){const s=i.container.lastElementChild.getBoundingClientRect().height*2;window.scrollBy({top:s,left:0,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
